apiVersion: apps/v1
kind: Deployment
metadata:
  name: techstackservice-deployment
  labels:
    app: techstackservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techstackservice
  template:
    metadata:
      labels:
        app: techstackservice
    spec:
      containers:
      - name: techstackservice
        image: techstackservice:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_REDIS_HOST
          value: "redis-service"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        volumeMounts:
        - name: log-volume
          mountPath: /app/logs
      volumes:
      - name: log-volume
        hostPath:
          path: /data/logs
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: techstackservice-service
spec:
  type: NodePort
  selector:
    app: techstackservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
